export const SIGN_IN_USER = "SIGN_IN_USER";
export const SIGN_IN_SUCCEEDED = "SIGN_IN_SUCCEEDED";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";

export const SIGN_UP_USER = "SIGN_UP_USER";
export const SIGN_UP_SUCCEEDED = "SIGN_UP_SUCCEEDED";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";

export const GET_USER_FROM_DB = "GET_USER_FROM_DB";
export const GET_USER_SUCCEEDED = "GET_USER_SUCCEEDED";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const UPDATE_EMAIL_SUCCEEDED = "UPDATE_EMAIL_SUCCEEDED";
export const UPDATE_EMAIL_FAILED = "UPDATE_EMAIL_FAILED";

export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_SUCCEEDED = "UPDATE_PASSWORD_SUCCEEDED";
export const UPDATE_PASSWORD_FAILED = "UPDATE_PASSWORD_FAILED";

export const UPDATE_FIRESTORE = "UPDATE_FIRESTORE";
export const UPDATE_FIRESTORE_SUCCEEDED = "UPDATE_FIRESTORE_SUCCEEDED";
export const UPDATE_FIRESTORE_FAILED = "UPDATE_FIRESTORE_FAILED";

export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const UPLOAD_IMAGE_FAILED = "UPLOAD_IMAGE_FAILED";