export const UPDATE_FIRESTORE = "UPDATE_FIRESTORE";
export const UPDATE_FIRESTORE_SUCCEEDED = "UPDATE_FIRESTORE_SUCCEEDED";
export const UPDATE_FIRESTORE_FAILED = "UPDATE_FIRESTORE_FAILED";

export const ADD_DOC_FIRESTORE = "ADD_DOC_FIRESTORE";
export const ADD_DOC_FIRESTORE_SUCCEEDED = "ADD_DOC_FIRESTORE_SUCCEEDED";
export const ADD_DOC_FIRESTORE_FAILED = "ADD_DOC_FIRESTORE_FAILED";

export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const UPLOAD_IMAGE_SUCCEEDED = "UPLOAD_IMAGE_SUCCEEDED";
export const UPLOAD_IMAGE_FAILED = "UPLOAD_IMAGE_FAILED";

export const REMOVE_ERROR = "REMOVE_ERROR";