export const OPEN_RECIPE_MODAL = "OPEN_RECIPE_MODAL";
export const CLOSE_RECIPE_MODAL = "CLOSE_RECIPE_MODAL";

export const CREATE_RECIPE = "CREATE_RECIPE";
export const CREATE_RECIPE_SUCCEEDED = "CREATE_RECIPE_SUCCEEDED";
export const CREATE_RECIPE_FAILED = "CREATE_RECIPE_FAILED";
